font:
  normal:
    family: 'Hack Nerd Font'
    style: Regular
  italic:
    family: 'Hack Nerd Font'
    style: Italic
  bold:
    family: 'Hack Nerd Font'
    style: Bold
  bold_italic:
    family: 'Hack Nerd Font'
    style: Bold Italic
  size: 10

  offset: # espaciado de las letras
    x: -1
    y: -1
  glyph_offset: # ubicacion de las letras
    x: -1
    y: -1

colors:
  primary:
    background: '#080b0a'
    foreground: '#ffffff'
    dim_foreground: '#ff0000' # Que es esto??
    bright_foreground: '#ff0000' # Que es esto??

  cursor:
    text: CellBackground
    cursor: CellForeground
  
  footer_bar:
    background: '#ff0000' # Que es esto??
    foregorund: '#ff0000' # Que es esto??

  selection:
    text: CellBackground
    background: '#219177'

  transparent_background_colors: false # transparencia a los fondos de distinto color

bell:
  animation: EaseOutSine
  duration: 200
  color: '#f5bc42'
  #command:
  # program: echo
  # args: ["Hellor, World!"]
