format = '$character$jobs$battery([[$all](fg:black bg:white)](white) )([$git_branch$git_status](fg:blue))$directory'
add_newline = false
palette = 'green'

[palettes.green]
darkgreen = '#0f7514'
lightgreen = '#7ed683'
lightblue = '#5397db'
red = '#e03d3d'
blue = '#375ae6'

[directory]
#format = '([[$read_only](fg:black bg:bright-purple)]($read_only_style)) [$path]($style) '
format = ' [$path]($style) '
truncation_length = 2
style = 'bold green'
#read_only = ' 󰉐 '
#read_only_style = 'bright-purple'

[[battery.display]]
threshold = 10

[python]
disabled = true

[git_branch]
format = '[$symbol]($style)'
symbol = ' '
style = 'italic bold black bg:blue'
#ignore_branches = ['main','master']

[git_commit]
disabled = true

[git_status]
format = '([$untracked$modified$ahead_behind$conflicted$ahead$behind$diverged$stashed$deleted$renamed$staged ]($style))'
untracked = ' 󰝒'
modified = ' 󰏫'
conflicted = ' 1'
ahead = ' 󰔪 '
behind = ' 3'
diverged = ' 4'
#up_to_date = ' 5' #indica que el repositorio se encuentra actualizado con la nuve <Desabilitado>
stashed = ' 6'
deleted = ' 󰆴'
renamed = ' 󰑕'
staged = ' 󱉲'
style = 'fg:black bg:blue'

[line_break]
disabled = true

[cmd_duration]
disabled = true

[sudo]
disabled = true #ver que hace

[jobs]
format = '[$symbol]($style) '
symbol = ''
symbol_threshold = 1
style = 'lightblue'

[character]
format = '$symbol '
success_symbol = '[](bold lightgreen)[](bold darkgreen)'
error_symbol ='[✖](bold red)'
